# Generated by Django 3.1.5 on 2021-01-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionesFinancieras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Instituciones Financiera',
                'verbose_name_plural': 'InstitucionesFinancieras',
            },
        ),
    ]
